RentSiteSolution/Controllers/ApartmentsShowController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RentSiteSolution.DATA;
using RentSiteSolution.DATA.Entity.Identity;

namespace RentSiteSolution.Controllers
{
    public class ApartmentsShowController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public ApartmentsShowController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public IActionResult AllApartmentsList(string title, int? minRooms, int? maxRooms, int? minPrice, int? maxPrice)
        {
            var query = _context.Apartments.Include(a => a.Photos).AsQueryable();

            // Применение фильтра по заголовку (названию) квартиры
            if (!string.IsNullOrEmpty(title))
            {
                query = query.Where(a => a.Title.Contains(title));
            }

            // Применение фильтра по количеству комнат
            if (minRooms.HasValue)
            {
                query = query.Where(a => a.Rooms >= minRooms.Value);
            }
            if (maxRooms.HasValue)
            {
                query = query.Where(a => a.Rooms <= maxRooms.Value);
            }

            // Применение фильтра по цене
            if (minPrice.HasValue)
            {
                query = query.Where(a => a.Price >= minPrice.Value);
            }
            if (maxPrice.HasValue)
            {
                query = query.Where(a => a.Price <= maxPrice.Value);
            }

            var apartments = query.ToList();
            return View(apartments);
        }


        // Метод для отображения страницы своих квартир
        [HttpGet]
        public async Task<IActionResult> MyApartments()
        {
            var currentUser = await _userManager.GetUserAsync(User);
            /*var userApartments = _context.Apartments.Where(a => a.UserId == currentUser.Id).ToList();*/
            var userApartments = _context.Apartments
        .Include(a => a.Photos) // Включаем все фотографии
        .Where(a => a.UserId == currentUser.Id)
        .ToList();
            return View(userApartments);
        }

        // Метод для отображения подробной информации о квартире
        public IActionResult ApartmentDetails(int id)
        {
            var apartment = _context.Apartments
        /*.Include(a => a.MainPhoto) // Включаем главную фотографию*/
        .Include(a => a.Photos) // Включаем все фотографии
        .FirstOrDefault(a => a.Id == id);
            return View(apartment);
        }
    }
}

RentSiteSolution/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClientMVCApartments</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css" asp-append-version="true">
    <!-- animate CSS -->
    <link rel="stylesheet" href="~/css/animate.css" asp-append-version="true">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="~/css/owl.carousel.min.css" asp-append-version="true">
    <!-- themify CSS -->
    <link rel="stylesheet" href="~/css/themify-icons.css" asp-append-version="true">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="~/css/flaticon.css" asp-append-version="true">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="~/css/magnific-popup.css" asp-append-version="true">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="~/css/slick.css" asp-append-version="true">
    <!-- style CSS -->
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> <img src="~/img/logo.png" alt="logo"> </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ApartmentsShow" asp-action="AllApartmentsList">Apartments</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="account-btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Account
                            </button>
                            <div class="dropdown-menu" aria-labelledby="account-btn">
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <form method="post" asp-controller="Account" asp-action="Logout" asp-route-returnUrl="/">
                                        <button type="submit" class="btn btn-link">Log Out</button>
                                    </form>
                                    <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="MyAccount">My Account</a>
                                }
                                else
                                {
                                    <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Login">Log In</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                                }
                            </div>
                        </div>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RentSiteProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <!-- jquery plugins here-->
    <!-- jquery -->
    <script src="~/js/jquery-1.12.1.min.js"></script>
    <!-- popper js -->
    <script src="~/js/popper.min.js"></script>
    <!-- bootstrap js -->
    <script src="~/js/bootstrap.min.js"></script>
    <!-- easing js -->
    <script src="~/js/jquery.magnific-popup.js"></script>
    <!-- swiper js -->
    <script src="~/js/swiper.min.js"></script>
    <!-- swiper js -->
    <script src="~/js/masonry.pkgd.js"></script>
    <!-- particles js -->
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <!-- swiper js -->
    <script src="~/js/slick.min.js"></script>
    <script src="~/js/jquery.counterup.min.js"></script>
    <script src="~/js/waypoints.min.js"></script>
    <!-- custom js -->
    <script src="~/js/custom.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RentSiteSolution/Views/Shared/_LayoutAccount.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClientMVCApartments</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css" asp-append-version="true">
    <!-- animate CSS -->
    <link rel="stylesheet" href="~/css/animate.css" asp-append-version="true">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="~/css/owl.carousel.min.css" asp-append-version="true">
    <!-- themify CSS -->
    <link rel="stylesheet" href="~/css/themify-icons.css" asp-append-version="true">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="~/css/flaticon.css" asp-append-version="true">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="~/css/magnific-popup.css" asp-append-version="true">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="~/css/slick.css" asp-append-version="true">
    <!-- style CSS -->
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> <img src="~/img/logo.png" alt="logo"> </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ApartmentsShow" asp-action="AllApartmentsList">Apartments</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="account-btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Account
                            </button>
                            <div class="dropdown-menu" aria-labelledby="account-btn">
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <form method="post" asp-controller="Account" asp-action="Logout" asp-route-returnUrl="/">
                                        <button type="submit" class="btn btn-link">Log Out</button>
                                    </form>
                                    <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="MyAccount">My Account</a>
                                }
                                else
                                {
                                    <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Login">Log In</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                                }
                            </div>
                        </div>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container-fluid">
        <div class="row">
            <div class="col-3 bg-light">
                @Html.Partial("_LeftMenu")
                <div class="fixed-bottom bg-light">
                    <!-- Футер боковой панели -->
                    <button type="button" class="btn btn-danger">Выход</button>
                </div>
            </div>
            <div class="col-9">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>

        <footer class="border-top footer text-muted fixed-bottom bg-light">
            <div class="container">
                &copy; 2023 - RentSiteProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <!-- jquery plugins here-->
        <!-- jquery -->
        <script src="~/js/jquery-1.12.1.min.js"></script>
        <!-- popper js -->
        <script src="~/js/popper.min.js"></script>
        <!-- bootstrap js -->
        <script src="~/js/bootstrap.min.js"></script>
        <!-- easing js -->
        <script src="~/js/jquery.magnific-popup.js"></script>
        <!-- swiper js -->
        <script src="~/js/swiper.min.js"></script>
        <!-- swiper js -->
        <script src="~/js/masonry.pkgd.js"></script>
        <!-- particles js -->
        <script src="~/js/owl.carousel.min.js"></script>
        <script src="~/js/jquery.nice-select.min.js"></script>
        <!-- swiper js -->
        <script src="~/js/slick.min.js"></script>
        <script src="~/js/jquery.counterup.min.js"></script>
        <script src="~/js/waypoints.min.js"></script>
        <!-- custom js -->
        <script src="~/js/custom.js"></script>
        @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RentSiteSolution/Views/Shared/_LeftMenu.cshtml
<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark min-vh-100" style="width: 280px;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
        <span class="fs-4">Боковая панель</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <a asp-area="" asp-controller="Account" asp-action="MyAccount" class="nav-link @(ViewContext.RouteData.Values["Action"].ToString() == "MyAccount" ? "active" : "") text-white">
                <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
                Информация
            </a>
        </li>
        <li>
            <a asp-area="" asp-controller="ApartmentsShow" asp-action="MyApartments" class="nav-link @(ViewContext.RouteData.Values["Action"].ToString() == "MyApartments" ? "active" : "") text-white">
                <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
                Мои квартиры
            </a>
        </li>
        <li>
            <a href="#" class="nav-link text-white">
                <svg class="bi me-2" width="16" height="16"><use xlink:href="#table"></use></svg>
                Договоры
            </a>
        </li>
        <li>
            <a href="#" class="nav-link text-white">
                <svg class="bi me-2" width="16" height="16"><use xlink:href="#grid"></use></svg>
                Документы
            </a>
        </li>
        <li>
            <a href="#" class="nav-link text-white">
                <svg class="bi me-2" width="16" height="16"><use xlink:href="#people-circle"></use></svg>
                Помощь
            </a>
        </li>
    </ul>
    <hr>
    <div class="dropdown mt-auto">
        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
            <strong>mdo</strong>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
            <li><a class="dropdown-item" href="#">Новый проект...</a></li>
            <li><a class="dropdown-item" href="#">Настройка</a></li>
            <li><a class="dropdown-item" href="#">Профиль</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Выйти</a></li>
        </ul>
    </div>
</div>